=== ialberdi/librafy/biblioteca.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


<xs:element name="biblioteca" type="bibliotecaInfo"/>


<xs:complexType name="bibliotecaInfo">
	<xs:sequence>
		<xs:element name="discos" type="discosInfo" />
        <xs:element name="libros" type="librosInfo" />
        <xs:element name="peliculas" type="peliculasInfo" />
    </xs:sequence>
</xs:complexType>

    
    <!-- ****************** 
    
    DEFINICIÓN PARA LOS DISCOS 
           
         ****************** -->
    
    <!-- Secuencia para el objeto disco -->
    <xs:complexType name="discosInfo">
		<xs:sequence>
        	<xs:element name="disco" type="discoInfo" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
	</xs:complexType>
    
    
    <!-- Elementos principales -->
    <xs:complexType name="discoInfo">
    	<xs:sequence>
    		<xs:element name="nombre" type="gTituloType" />
			<xs:element name="productores" type="gProductoresInfo" />
			<xs:element name="editor" type="editorInfo" />
			<xs:element name="anio" type="gAnioInfo" />
			<xs:element name="canciones" type="cancionesInfo"/>
    	</xs:sequence>
    	<xs:attribute name="id" type="xs:integer" use="required"/>
    </xs:complexType>

	<!-- Editores -->
	 <xs:complexType name="editorInfo">
		<xs:simpleContent>
			<xs:extension base="editorEnumInfo">
				<xs:attributeGroup ref="gPersonasAtributosInfo"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>


	<xs:simpleType name="editorEnumInfo">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Anthony Baletti" />
			<xs:enumeration value="John Smith" />
			<xs:enumeration value="Erik Molier" />
		</xs:restriction>
	</xs:simpleType>

    
    <!-- Canciones -->
    <xs:complexType name="cancionesInfo">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="1"  name="cancion" type="cancionInfo"/>
		</xs:sequence>
	</xs:complexType>
	
	
	<xs:complexType name="cancionInfo">
    	<xs:sequence>
    		<xs:element name="titulo" type="gTituloType" />
			<xs:element name="compositores" type="compositoresInfo" />
			<xs:element name="duracion" type="gDuracionInfo" />
			<xs:element name="interpretes" type="interpretesInfo" />
    	</xs:sequence>
    	<xs:attribute name="id" type="xs:integer" use="required"/>
    </xs:complexType>
    
   	<xs:complexType name="compositoresInfo">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="1"  name="compositor" type="gPersonaInfo"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="interpretesInfo">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="1"  name="interprete" type="gPersonaInfo"/>
		</xs:sequence>
	</xs:complexType>
    

    <!-- ****************** 
    
    FINAL DE LA DEFINICIÓN PARA LOS DISCOS 
           
         ****************** -->
    

    <!-- ****************** 
    
    DEFINICIÓN PARA LOS LIBROS 
           
         ****************** -->
    
    <!-- Secuencia para el objeto disco -->
    <xs:complexType name="librosInfo">
		<xs:sequence>
        	<xs:element name="libro" type="libroInfo" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
	</xs:complexType>
    
    
    <!-- Elementos principales -->
    <xs:complexType name="libroInfo">
    	<xs:sequence>
    		<xs:element name="titulo" type="gTituloType" />
			<xs:element name="autores" type="autoresInfo" />
			<xs:element name="lengua" type="lenguaInfo" />
			<xs:element name="genero" type="generoInfo" />
			<xs:element name="fecha" type="fechaInfo" />
			<xs:element name="resena" type="xs:string"  />
    	</xs:sequence>
    	<xs:attribute name="id" type="xs:integer" use="required"/>
    </xs:complexType>
    
    <!-- Autores -->
   	<xs:complexType name="autoresInfo">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="1"  name="autor" type="gPersonaInfo"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Lengua -->
	<xs:simpleType name="lenguaInfo">
	    <xs:restriction base="xs:string">
	        <xs:pattern value="[a-z][a-z]-[A-Z][A-Z]"/>
	    </xs:restriction>
	</xs:simpleType>
	
	<!-- Genero -->
	<xs:simpleType name="generoInfo">
    	<xs:restriction base="xs:string">
    		<xs:enumeration value="Policial" />
    		<xs:enumeration value="Romántica" />
    		<xs:enumeration value="Aventura" />
    		<xs:enumeration value="Terror" />
    		<xs:enumeration value="Ficción" />
    		<xs:enumeration value="Ciencia" />
    		<xs:enumeration value="Biográfica" />
    		<xs:enumeration value="Infantil" />
        </xs:restriction>
    </xs:simpleType>
    
   	<!-- Fecha -->
	<xs:simpleType name="fechaInfo">
		<xs:restriction base="xs:date">
			<xs:minInclusive value="1500-01-01"/>
			<xs:maxInclusive value="2100-12-31"/>
			<xs:pattern value=".{10}"/>
		</xs:restriction>
	</xs:simpleType>
	


    <!-- ****************** 
    
    FINAL DE LA DEFINICIÓN PARA LOS LIBROS 
           
         ****************** -->
        
    
    

     <!-- ****************** 
    
    DEFINICIÓN PARA LOS PELÍCULAS 
           
         ****************** -->
    
    <!-- Secuencia para el objeto libro -->
    <xs:complexType name="peliculasInfo">
		<xs:sequence>
        	<xs:element name="pelicula" type="peliculaInfo" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
	</xs:complexType>
    
    
    <!-- Elementos principales -->
    <xs:complexType name="peliculaInfo">
    	<xs:sequence>
    		<xs:element name="titulo" type="gTituloType" />
			<xs:element name="duracion" type="gDuracionInfo" />
			<xs:element name="anio_estreno" type="gAnioInfo" />
			<xs:element name="directores" type="directoresInfo" />
			<xs:element name="productores" type="gProductoresInfo" />
			<xs:element name="actores" type="actoresInfo"/>
    	</xs:sequence>
    	<xs:attribute name="id" type="xs:integer" use="required"/>
    </xs:complexType>
    
    <!-- Directores -->
   	<xs:complexType name="directoresInfo">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="1"  name="director" type="gPersonaInfo"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Actores -->
   	<xs:complexType name="actoresInfo">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="1"  name="actor" type="gPersonaInfo"/>
		</xs:sequence>
	</xs:complexType>
	


    <!-- ****************** 
    
    FINAL DE LA DEFINICIÓN PARA LOS PELÍCULAS 
           
         ****************** --> 
    

    
    <!-- ****************** 
    
           TIPOS GLOBALES 
           
         ****************** -->
    
    <!-- titulos y nombres -->
    <xs:simpleType name="gTituloType">
    	<xs:restriction base="xs:string">
    		<xs:minLength value="1" />
            <xs:maxLength value="80" />
        </xs:restriction>
    </xs:simpleType>
    
    <!-- personas con atributos de codigo identificativo y nacionalidad. Ejemplo: autores, productores, etc. -->
    <xs:complexType name="gPersonaInfo">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attributeGroup ref="gPersonasAtributosInfo"/>
			</xs:extension>
		</xs:simpleContent>
    </xs:complexType>
    
    <!-- Atributos de las personas como autores, productores, editores, etc. -->
    <xs:attributeGroup name="gPersonasAtributosInfo">
    	<xs:attribute name="codigo" type="gCodigoType" use="required"/>
		<xs:attribute name="nacionalidad" type="gTituloType" use="required"/>
    </xs:attributeGroup>

	<xs:simpleType name="gCodigoType">
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9]{6})"/>
		</xs:restriction>
	</xs:simpleType>

    
    <!-- Productores para discos y películas -->
   	<xs:complexType name="gProductoresInfo">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="1"  name="productor" type="gPersonaInfo"/>
		</xs:sequence>
	</xs:complexType>
    
    <!-- Años -->
    <xs:simpleType name="gAnioInfo">
    	<xs:restriction base="xs:integer">
    		<xs:minInclusive  value="1900" />
            <xs:maxInclusive   value="3000" />
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Duración -->
    <xs:simpleType name="gDuracionInfo">
    	<xs:restriction base="xs:time">
    		<xs:minInclusive  value="00:00:01" />
            <xs:maxInclusive   value="23:59:59" />
        </xs:restriction>
    </xs:simpleType>


</xs:schema>

=== ialberdi/librafy/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="biblioteca.xsd">
  <discos>
    <disco id="1">
      <nombre>Tubular bells 2</nombre>
      <productores>
        <productor codigo="365895" nacionalidad="canadiense">Jennifer McNeal</productor>
        <productor codigo="458958" nacionalidad="británica">Mike Oldfield</productor>
      </productores>
      <editor codigo="596859" nacionalidad="británica">Anthony Baletti</editor>
      <anio>1997</anio>
      <canciones>
        <cancion id="1">
          <titulo>Sentinel</titulo>
          <compositores>
            <compositor codigo="120336" nacionalidad="británica">Mikel Oldfield</compositor>
            <compositor codigo="748554" nacionalidad="estadounidense">Susanne Smith</compositor>
          </compositores>
          <duracion>00:08:06</duracion>
          <interpretes>
            <interprete codigo="121220" nacionalidad="británica">Mike Oldfield 1</interprete>
            <interprete codigo="122220" nacionalidad="británica">Mike Oldfield 2</interprete>
            <interprete codigo="123220" nacionalidad="británica">Mike Oldfield 3</interprete>
          </interpretes>
        </cancion>
        <cancion id="2">
          <titulo>Dark Star</titulo>
          <compositores>
            <compositor codigo="487584" nacionalidad="británica">Mikel Oldfield</compositor>
            <compositor codigo="658998" nacionalidad="británica">Mikel Oldfield</compositor>
            <compositor codigo="325448" nacionalidad="británica">Mikel Oldfield</compositor>
          </compositores>
          <duracion>00:02:16</duracion>
          <interpretes>
            <interprete codigo="956558" nacionalidad="británica">Mike Oldfield</interprete>
          </interpretes>
        </cancion>
        <cancion id="3">
          <titulo>Hello World</titulo>
          <compositores>
            <compositor codigo="145558" nacionalidad="británica">Mikel Oldfield</compositor>
          </compositores>
          <duracion>00:03:28</duracion>
          <interpretes>
            <interprete codigo="120003" nacionalidad="británica">Mike Oldfield</interprete>
          </interpretes>
        </cancion>
      </canciones>
    </disco>
    <disco id="2">
      <nombre>Tubular bells 3</nombre>
      <productores>
        <productor codigo="965885" nacionalidad="canadiense">Jennifer McNeal</productor>
        <productor codigo="120332" nacionalidad="británica">Mike Oldfield</productor>
      </productores>
      <editor codigo="658998" nacionalidad="británica">Anthony Baletti</editor>
      <anio>1999</anio>
      <canciones>
        <cancion id="1">
          <titulo>The Source of Secrets</titulo>
          <compositores>
            <compositor codigo="959889" nacionalidad="británica">Mikel Oldfield</compositor>
            <compositor codigo="102114" nacionalidad="estadounidense">Susanne Smith</compositor>
          </compositores>
          <duracion>00:01:06</duracion>
          <interpretes>
            <interprete codigo="326558" nacionalidad="británica">Mike Oldfield</interprete>
          </interpretes>
        </cancion>
        <cancion id="2">
          <titulo>The Watchful Eye</titulo>
          <compositores>
            <compositor codigo="120114" nacionalidad="británica">Mikel Oldfield</compositor>
          </compositores>
          <duracion>00:09:16</duracion>
          <interpretes>
            <interprete codigo="120225" nacionalidad="británica">Mike Oldfield</interprete>
          </interpretes>
        </cancion>
      </canciones>
    </disco>
    <disco id="3">
      <nombre>Tubular bells 1</nombre>
      <productores>
        <productor codigo="120225" nacionalidad="canadiense">Jennifer McNeal</productor>
        <productor codigo="120114" nacionalidad="británica">Mike Oldfield</productor>
      </productores>
      <editor codigo="252669" nacionalidad="británica">Anthony Baletti</editor>
      <anio>1997</anio>
      <canciones>
        <cancion id="1">
          <titulo>Sentinel</titulo>
          <compositores>
            <compositor codigo="120225" nacionalidad="británica">Mikel Oldfield</compositor>
            <compositor codigo="895558" nacionalidad="estadounidense">Susanne Smith</compositor>
          </compositores>
          <duracion>00:08:06</duracion>
          <interpretes>
            <interprete codigo="120225" nacionalidad="británica">Mike Oldfield</interprete>
          </interpretes>
        </cancion>
        <cancion id="2">
          <titulo>Dark Star</titulo>
          <compositores>
            <compositor codigo="565889" nacionalidad="británica">Mikel Oldfield</compositor>
          </compositores>
          <duracion>00:02:16</duracion>
          <interpretes>
            <interprete codigo="858774" nacionalidad="británica">Mike Oldfield</interprete>
          </interpretes>
        </cancion>
        <cancion id="3">
          <titulo>Hello World</titulo>
          <compositores>
            <compositor codigo="120224" nacionalidad="británica">Mikel Oldfield</compositor>
          </compositores>
          <duracion>00:03:28</duracion>
          <interpretes>
            <interprete codigo="958457" nacionalidad="británica">Mike Oldfield</interprete>
          </interpretes>
        </cancion>
      </canciones>
    </disco>
    <disco id="4">
      <nombre>Tubular bells 4</nombre>
      <productores>
        <productor codigo="958774" nacionalidad="canadiense">Jennifer McNeal</productor>
        <productor codigo="265885" nacionalidad="británica">Mike Oldfield</productor>
      </productores>
      <editor codigo="625369" nacionalidad="británica">Anthony Baletti</editor>
      <anio>1997</anio>
      <canciones>
        <cancion id="1">
          <titulo>Sentinel</titulo>
          <compositores>
            <compositor codigo="958558" nacionalidad="británica">Mikel Oldfield</compositor>
            <compositor codigo="625998" nacionalidad="estadounidense">Susanne Smith</compositor>
          </compositores>
          <duracion>00:08:06</duracion>
          <interpretes>
            <interprete codigo="235665" nacionalidad="británica">Mike Oldfield</interprete>
          </interpretes>
        </cancion>
        <cancion id="2">
          <titulo>Dark Star</titulo>
          <compositores>
            <compositor codigo="125447" nacionalidad="británica">Mikel Oldfield</compositor>
          </compositores>
          <duracion>00:02:16</duracion>
          <interpretes>
            <interprete codigo="859887" nacionalidad="británica">Mike Oldfield</interprete>
          </interpretes>
        </cancion>
        <cancion id="3">
          <titulo>Hello World</titulo>
          <compositores>
            <compositor codigo="125447" nacionalidad="británica">Mikel Oldfield</compositor>
          </compositores>
          <duracion>00:03:28</duracion>
          <interpretes>
            <interprete codigo="154774" nacionalidad="británica">Mike Oldfield</interprete>
          </interpretes>
        </cancion>
      </canciones>
    </disco>
    <disco id="5">
      <nombre>Tubular bells 5</nombre>
      <productores>
        <productor codigo="236558" nacionalidad="Nac1111">Productor1</productor>
        <productor codigo="254774" nacionalidad="Nac2222">Productor2</productor>
        <productor codigo="203021" nacionalidad="Nac3333">Productor3</productor>
      </productores>
      <editor codigo="365885" nacionalidad="canadiense">Anthony Baletti</editor>
      <anio>1995</anio>
      <canciones>
        <cancion id="1">
          <titulo>Cancion 1</titulo>
          <compositores>
            <compositor codigo="985441" nacionalidad="Cancion1Compositor1Nac1">Cancion1Compositor1</compositor>
            <compositor codigo="955847" nacionalidad="Cancion1Compositor2Nac2">Cancion1Compositor2</compositor>
          </compositores>
          <duracion>00:01:11</duracion>
          <interpretes>
            <interprete codigo="325441" nacionalidad="Cancion1Interprete1Nac1">Cancion1Interprete1</interprete>
          </interpretes>
        </cancion>
        <cancion id="2">
          <titulo>Cancion 2</titulo>
          <compositores>
            <compositor codigo="954774" nacionalidad="Cancion2Compositor1Nac1">Cancion2Compositor1</compositor>
          </compositores>
          <duracion>00:02:22</duracion>
          <interpretes>
            <interprete codigo="326585" nacionalidad="Cancion2Interprete1Nac1">Cancion2Interprete1</interprete>
          </interpretes>
        </cancion>
        <cancion id="3">
          <titulo>Cancion 3</titulo>
          <compositores>
            <compositor codigo="625884" nacionalidad="Cancion3Compositor1Nac1">Cancion3Compositor1</compositor>
            <compositor codigo="958774" nacionalidad="Cancion3Compositor2Nac1">Cancion3Compositor2</compositor>
            <compositor codigo="252524" nacionalidad="Cancion3Compositor3Nac1">Cancion3Compositor3</compositor>
          </compositores>
          <duracion>00:03:33</duracion>
          <interpretes>
            <interprete codigo="658995" nacionalidad="Cancion3Interprete1Nac1">Cancion3Interprete1</interprete>
          </interpretes>
        </cancion>
      </canciones>
    </disco>
    <disco id="6">
      <nombre>Nuevo disco de prueba</nombre>
      <productores>
        <productor codigo="989885" nacionalidad="canadiense">Productor</productor>
      </productores>
      <editor codigo="232551" nacionalidad="1">John Smith</editor>
      <anio>2018</anio>
      <canciones>
        <cancion id="1">
          <titulo>Cancion 1</titulo>
          <compositores>
            <compositor codigo="365889" nacionalidad="estadounidense">Compositor 1</compositor>
          </compositores>
          <duracion>00:30:55</duracion>
          <interpretes>
            <interprete codigo="125774" nacionalidad="francés">Interprete 1</interprete>
          </interpretes>
        </cancion>
